
site_name: Tree garden documentation
site_author: miob

nav:
  - Home: index.md
  - examples:
    - Do  something: examples/example1.md
    - Do  something other: examples/example2.md
  - api:
    - item1: api/koko.md
    - item2: api/kuku.md

extra:
  homepage: others/logo_will_eat_you

theme:
  name: material
  logo: resources/images/tree.svg
  favicon: resources/images/tree.svg
  custom_dir: overrides
  features:
#    - navigation.tabs
#    - navigation.tracking
    - navigation.sections


docs_dir: pages
dev_addr: 0.0.0.0:9009

watch:
  - pages
  - hooks
  - code_snippets
  - overrides

hooks:
  - ./hooks/start.py
  - ./hooks/ts_code_snippet.py



# code highlighting not configured out of the box!
# https://github.com/squidfunk/mkdocs-material/issues/156
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      baselevel: 2

