
site_name: Tree garden documentation
site_author: miob

# main structure of docs
nav:
  - Home: index.md
  - Getting started: gettingStarted.md

  - Important Basics: importantBasics.md
  - Examples:
    - Import dataset from JSON: examples/importJsonWithTypescript.md
    - Configuration from data sample: examples/configurationFromSingleDataSample.md
  - Playground: playground.md # hide later
  # api pages are added to navigation by docs/hooks/hack_typedoc_into_docs.py hook
  - api_docs:
    - index: api/modules.md


# tweaks

docs_dir: pages

extra_css:
  - resources/css/custom.css

# If you want different goto when click on logo - by default home is used
#extra:
#  homepage: https://example.com

theme:
  name: material
  palette:
    primary: blue grey
#      accent: green
  logo: resources/images/tree.svg
#  icon:
#    logo: material/forest
  favicon: resources/images/tree.svg
  custom_dir: overrides
  features:
#    - navigation.tabs
#    - navigation.tracking
    - navigation.sections
#    - toc.integrate

dev_addr: 0.0.0.0:9009

watch:
  - pages
  - hooks
  - code_snippets
  - overrides

hooks:
  - ./hooks/start.py
  - ./hooks/ts_code_snippet.py
  - ./hooks/hack_typedoc_into_docs.py




markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      baselevel: 1

  # code highlighting not configured out of the box!
  # https://github.com/squidfunk/mkdocs-material/issues/156
  - pymdownx.highlight
  - pymdownx.details

  # diagrams extension
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list

  #mathjax setting
  - pymdownx.arithmatex:
      generic: true

# all scripts are because of mathjax
extra_javascript:
  - resources/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


