name: 'Publish code, docs, deploy docs'

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: You can bump major, minor or patch version
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
        default: patch
        required: true
      changeLog:
        type: string
        required: false
        description: What does changed?
        default: Changelog not known


jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:16-buster
      options: --user root
    outputs:
      new_version: ${{ steps.version_output.outputs.new_version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install deps # needed for run tests + transpile typescript
        run: npm ci

      - name: hack because of issue # https://github.com/actions/runner-images/issues/6775
        run: git config --global --add safe.directory /__w/treeGarden/treeGarden

      - name: Bump version and create and push tag
        run: bash ./scripts/versionAndTag.sh ${{ github.event.inputs.versionType }} ${{ secrets.GITHUB_TOKEN }}

      - name: New version to env variable
        run: echo "NEW_VERSION=v$(node scripts/logPackageVersion.js)" >> $GITHUB_ENV

      # new version without 'v' to job output
      - name: New version as job output
        id: version_output
        run: echo "new_version=$(node scripts/logPackageVersion.js)" >> $GITHUB_OUTPUT

      - name: Transpile typescript (build)
        run: npm run build

      - name: Create .npmrc with access token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc

      - name: Publish package on npm
        run: npm publish

      - name: Create github release
        if:  ${{ contains(fromJson('["major", "minor", "patch"]'), github.event.inputs.versionType ) }}
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.inputs.changeLog }}
          tag_name: ${{ env.NEW_VERSION }}

  #https://github.com/marketplace/actions/build-and-push-docker-images
  docs_docker_image:
    if:  ${{ contains(fromJson('["major", "minor", "patch"]'), github.event.inputs.versionType ) }}
    needs:
      - publish
    runs-on: ubuntu-latest

    steps:
      - name: Echo new version
        run: echo "New version = ${{needs.publish.outputs.new_version}}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'miob01'
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push docs container
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docs/Dockerfile
          tags: miob01/tree-garden-docs:${{needs.publish.outputs.new_version}},miob01/tree-garden-docs:latest

  deploy_docs:
    if:  ${{ contains(fromJson('["major", "minor", "patch"]'), github.event.inputs.versionType ) }}
    needs:
      - docs_docker_image
      - publish
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:3.10.2
      options: --user root


    steps:
      - name: Echo new version
        run: echo "New version = ${{needs.publish.outputs.new_version}}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare kubeconf
        run: echo {{secrets.KUBE_CONF_BASE64}} | base64 -d > kube.conf

      - name: Deploy to DOKS
        run: export KUBECONFIG=kube.conf && helm upgrade --set image_version=${{needs.publish.outputs.new_version}} --install -n tree-garden tree-garden-dox ./helm_charts/tree-garden-docs/




