name: Publish

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: You can bump major, minor or patch version
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
        default: patch
        required: true
      changeLog:
        type: string
        required: false
        description: What does changed?
        default: Changelog not known


jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:16-buster
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install deps # needed for run tests + transpile typescript
        run: npm ci

      - name: Bump version and create and push tag
        run: bash ./scripts/versionAndTag.sh ${{ github.event.inputs.versionType }} ${{ secrets.GITHUB_TOKEN }}

      - name: New version to env variable
        run: echo "NEW_VERSION=v$(node scripts/logPackageVersion.js)" >> $GITHUB_ENV

      - name: Transpile typescript (build)
        run: npm run build

      - name: Create .npmrc with access token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc

      - name: Publish package on npm
        run: npm publish

      - name: Create github release
        if:  ${{ contains(fromJson('["major", "minor", "patch"]'), github.event.inputs.versionType ) }}
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.inputs.changeLog }}
          tag_name: ${{ env.NEW_VERSION }}



