name: 'tree-garden types and test'
# todo lot of duplicity - fix

on:
  push:
    branches:
      - 'master'



jobs:
  install_deps:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16

    steps:
      - name: 'Checkout code - as we need package.json + lock'
        uses: actions/checkout@v3

      - name: 'Cache based on package.lock.json '
        id:  'node_modules_cache'
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node_modules_cache_${{ hashFiles('package-lock.json') }}

      -  if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
         name: 'Install node dependencies if no cache hit'
         run: npm ci


  unit-tests:

    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16
    needs: [install_deps]

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Cache based on package.lock.json '
        id: 'node_modules_cache'
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node_modules_cache_${{ hashFiles('package-lock.json') }}


      - name: 'Run unit tests'
        run: npm run test

